### ISSUE TITLE
Can't remove eventBustListener?

### ISSUE THREAD

**Issue by thibka** [jcalixte/retrobus#14]
Hi, 

I'm having an issue trying to clear an event listener.   
It looks like removeEventBusListener / clearEventBusListeners have no effect, unless I misunderstanding something...

I've created a minimal codepen demo of the issue:
https://codepen.io/Thibka/pen/gOeOXPb?editors=0012

Thanks

**Comment by thibka** [comment]
So what I actually needed was a way to clear the previous already emitted events. 
This can be super useful when you have to handle retroactive events, because you often need to make sure they don't cumulate.

How about adding a method like this

```javascript
/**
 * Clear all emitted events.
 * @param name event name.
 */
 export const clearEmittedEvents = (name) => {
    if (name === undefined) {
        emittedEvents.clear();
        return;
    }
    emittedEvents.delete(name);
};
```

I would create a merge request, but you're working with typescript and I'm not comfortable with that!

**Comment by jcalixte** [comment]
Hi!
`removeEventBusListener` and `clearEventBusListeners` remove the listeners for a specific event, not the emitted events. I updated your [codepen demo](https://codepen.io/juliencalixte/pen/OJvPwgP).

Though, your method is relevant, I'll implement it 👍🏽

**Comment by jcalixte** [comment]
Should be ok in 1.9.2 🙂
